import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useMoralis } from "react-moralis";
import Layout from '../components/layout'
import Header from "../components/Header"
import { Button, Badge, Stack, HStack, Grid, Flex, Spacer, Text } from "@chakra-ui/react"
import Footer from "../components/Footer"
import Feed from "../components/Feed"


export default function Home() {

  const { authenticate, isAuthenticated, logout, user } = useMoralis();



  return (
    <div className={styles.container}>
      <Head>
        <title>molly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <main className={styles.main}>
      <Feed/>
      </main>
      <Footer/>


    </div>
  )
}
